GET http://localhost:8080/comments

###

GET http://localhost:8080/comments/1

###

POST http://localhost:8080/comments
Content-Type: application/json

{
    "name": "asd",
    "body": "sdd",
    "mail": "sdsd"
}

###

DELETE http://localhost:8080/comments/0

###

PATCH http://localhost:8080/comments/1
Content-Type: application/json

{
    "name": "g",
    "body": "u",
    "mail": "d"
}